---
- name: Deploy VMs
  hosts: aap_nodes
  gather_facts: false

  tasks:
    - ansible.builtin.include_role:
        name: vmware_vm
        tasks_from: deploy

#- name: Add VM to Satellite
#- name: DNS
#- name: Install AAP
#- name: Provision AAP
#- name: Configure HAProxy
