---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-minimal-rhel8'
  EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8:latest'

ansible_config: '../../../.ansible.cfg'

dependencies:
  galaxy: collections/requirements.yml
  python: requirements.txt
  system: bindep.txt

#additional_build_steps:
#  prepend: |
#    RUN microdnf module enable postgresql:12 -y
