# Set up Stork for Kea monitoring
- name: Prepare database
  hosts: stork_db
  become: postgres
  collections:
    - community.postgresql

  tasks:
    - name: psycopg2 dependency (BSD)
      become: yes
      pkgng:
        name: py37-psycopg2
        state: present
        
    - name: "Stork Database - User"
      postgresql_user:
        name: stork
        password: "{{ stork_pg_pass }}"
        comment: "Stork User"

    - name: "Stork Database - Database"
      postgresql_db:
        name: stork

    - name: "Stork Database - Permission"
      postgresql_privs:
        db: postgres
        role: stork
        type: database
        obj: stork
        privs: ALL

    - name: "Stork Database - Crypto Extension"
      postgresql_ext:
        db: stork
        name: pgcrypto
        state: present
  
- name: Stork Agent Installation
  hosts: pi1.mgmt.toal.ca
  become: true

  tasks:
    - name: RPM Key for ISC
      rpm_key:
        state: present
        fingerprint: 7AB5064B08F069A1A5CC500C77F64EC28053D1FB
        key: https://dl.cloudsmith.io/public/isc/stork/gpg.77F64EC28053D1FB.key
    
    - name: Stork RPM installed
      dnf:
        name:
         - http://webserver.mgmt.toal.ca/isc-stork-agent-0.18.0.210708184529-1.aarch64.rpm
        disable_gpg_check: yes
        state: present

        # Firewall & Service

- name: Stork Server Installation
  hosts: stork_server
  become: true

  tasks:
    - name: RPM Key for ISC
      rpm_key:
        state: present
        fingerprint: 7AB5064B08F069A1A5CC500C77F64EC28053D1FB
        key: https://dl.cloudsmith.io/public/isc/stork/gpg.77F64EC28053D1FB.key

    # - name: Stork Server RPM Installed
    #   dnf:
    #     name: 

    - name: Stork Server configuration
      template:
        src: stork_server.env
        dest: /etc/stork/server.env
        mode: 0640
        group: root
        owner: root
      notify: Stork Restart

    - name: Stork Server Enabled
      service:
        name: isc-stork-server
        enabled: true

  handlers:

    - name: Stork Restart
      service: 
        name: isc-stork-server
        state: restarted